DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME CLOB
);

CREATE TABLE LEAVE_REQUESTS
(
    ID INTEGER PRIMARY KEY NOT NULL ,
    DATESTART TIMESTAMP,
    DATEEND TIMESTAMP NOT NULL,
    COUNTDAYS INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT ORDERS_TO_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);